### ISSUE TITLE
récupérer les lieux d'un type donné dans une zone

### ISSUE THREAD

**Issue by TheYoloToto** [Tagtwim912/Hyblab2021#2]
récupérer tous les lieux d'une zone
- params : 
  - zone = polygone OU point GPS (centre) + rayon -> à voir selon l'API utilisée ce qui est le plus pratique
  - liste des types de lieux voulus (définir une liste en dur de types de lieux, elle sera réutilisée dans la page 'carte')
- OpenDataNantes (a priori)

**Comment by ghost** [comment]
Le paramètre de zone est finalement la bbox, c'est plus simple. Tout a été plus ou moins implémenté donc c'est cool cool
