### ISSUE TITLE
faciliter la saisie d'un point GPS par l'utilisateur

### ISSUE THREAD

**Issue by TheYoloToto** [Tagtwim912/Hyblab2021#3]
convertir la saisie d'une adresse (texte) en point GPS
API : OpenRoutesServices, Google Maps, ...
utiliser la géolocalisation pour récupérer le point GPS de l'utilisateur
-> mécanique native des navigateur, voir le doc de Javascript (MDN)

**Comment by ghost** [comment]
Çacéfé
